namespace: helloworld


image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

secrets:
  DB_HOST: helloworddev123.mysql.database.azure.com
  DB_NAME: helloword
  DB_USER: helloworld
  DB_PASSWORD: dDWioih2d54wqwq3
